### ISSUE TITLE
Rename template

### ISSUE THREAD

**Issue by pvalentim** [studio-206/nextjs-typescript-stitches-template#19]
The name shouldn't reflect implementation details, instead should state its purpose.

Since we're going to have a few template soon I would suggest this one to be something like:
`website-template`

**Comment by fabioruolo** [comment]
the current template could then be renamed to something like `without-cms-template` or `frontend-template`?

**Comment by karltaylor** [comment]
`frontend-template` sounds good, fits all use-cases for websites / apps / saas / products etc.
